baseURL = "https://axiom-example.netlify.app"

title = "Youngjoon Lee"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 2
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts"]
copyrightYear = 2020
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "2006-01-02 15:04 MST"
highlight = "dark"

[params.brand]
domain = "youngjoon-lee.github.io"
email = "taxihighway@gmail.com"

[params.social]
github = "https://github.com/youngjoon-lee"
linkedin = "https://www.linkedin.com/in/youngjoon-lee-11ba7b72/"
footer = ["github", "linkedin"]

[params.services]
analyticsId = "UA-144368893-2"
adwordsId = ""
adsenseId = ""
adsenseAdSlotId = ""
adsenseLoad = ""
adwordsConversionId = ""
adwordsConversionValue = 0
facebookApp = ""
facebookPixel = ""
disqusShortname = ""

[params.logo]
inline = false
path = ""

[params.image]
width = "2048"
height = "1024"
faviconIco = "favicon.ico"
faviconAlt = "image/brand/favicon.png"
icon1To1 = "image/brand/icon-1-1.png"
icon2To1 = "image/brand/icon-2-1.png"
default = "image/page-default.webp"

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

[params.cloudinary]
host = "https://res.cloudinary.com/CLOUD_NAME/"
version = ""
image = "image/upload/"
raw = "raw/upload/"
video = "video/upload/"

[params.cloudinary.presets]
base = "f_auto,q_auto/"
page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/posts/"
name = "Posts"
weight = 1

[[menu.foot]]
url = "/about/"
name = "About"
weight = 2

[[menu.foot]]
url = "/contact/"
name = "Contact"
weight = 3

[[menu.foot]]
url = "/privacy/"
name = "Privacy"
weight = 4

[languages]
[languages."en"]
weight = 1
languageName = "English"
