languageCode = "en-us"
title = "Youngjoon Lee"
theme = "smol"
staticDir = ["static"]
googleAnalytics = "UA-144368893-2"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/youngjoon-lee"
        weight = 1 

  [[menu.footer]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/youngjoon-lee-11ba7b72/"
        weight = 2 

  [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 
